Post cart item now is LIVE 🚀
JSD-0423/backend-final-2 pull request #32
Opened 2023-07-18 06:28 UTC by yusufmsabeh

2023-07-19 07:02 UTC, mshareef-kiitos requested changes

2023-07-19 07:02 UTC, mshareef-kiitos commented on src/middlewares/error-handler.ts
> +  console.log("error ", error);
Remove consoles

2023-07-19 07:02 UTC, mshareef-kiitos commented on src/models/Cart.ts
> +          "SELECT SUM(cart_products.quantity * products.price) AS totalPrice FROM cart_products JOIN products ON cart_products.product_id = products.id WHERE cart_id = ?",
Why not to use sequelize features to achieve this?

2023-07-19 07:02 UTC, mshareef-kiitos commented on src/models/User.ts
> +      cart = await user.$create<Cart>("cart", {});
No cart details at this stage?

2023-07-19 07:02 UTC, mshareef-kiitos commented on src/routes/carts.ts
> +router.use(passport.authenticate("jwt", { session: false }));
Passport 😍

2023-07-19 07:02 UTC, mshareef-kiitos commented on src/models/User.ts
> +      await user.$get("carts", {
The parameter could be `userId` instead of `user`. And here, you can use the sequelize feature: `findOrCreate()` and use the `userId` in the where statement (instead of using the `user` table).

2023-07-19 08:28 UTC, yusufmsabeh commented on src/models/User.ts
> +      cart = await user.$create<Cart>("cart", {});
The cart's details have default values, That's why the cart's details not provided

2023-07-19 12:22 UTC, yusufmsabeh commented on src/models/Cart.ts
> +          "SELECT SUM(cart_products.quantity * products.price) AS totalPrice FROM cart_products JOIN products ON cart_products.product_id = products.id WHERE cart_id = ?",
I have been attempting to achieve it for an hour now, but it seems impossible to accomplish using Sequelize. The problem lies in the fact that Sequelize automatically adds numerous columns to the select query, and it does not provide an option to exclude them. As a result, the SUM function cannot be executed successfully, even when using the GROUP BY clause.
sequelize query:

```sql
SELECT 
    `Product`.`id`,
    `Product`.`title`,
    `Product`.`description`,
    `Product`.`price`,
    `Product`.`rate`,
    `Product`.`isLimited`,
    `Product`.`discount`,
    `Product`.`discount_type`,
    `Product`.`createdAt`,
    `Product`.`updatedAt`,
    `Product`.`category_id`,
    `Product`.`brand_id`,
    SUM(quantity * price) AS `totalPrice`,
    `CartProduct`.`product_id` AS `CartProduct.product_id`,
    `CartProduct`.`cart_id` AS `CartProduct.cart_id`,
    `CartProduct`.`quantity` AS `CartProduct.quantity`
FROM
    `products` AS `Product`
        INNER JOIN
    `cart_products` AS `CartProduct` ON `Product`.`id` = `CartProduct`.`product_id`
        AND `CartProduct`.`cart_id` = 9;

```
this is my Code:
```ts
    const products = await cart.$get("products", {
      attributes: {
        include: [
          [
            connection.fn(
              "sum",
              connection.literal("quantity*price")
            ),
            "totalPrice",
          ],
        ]
      },

    });
```

2023-07-19 16:16 UTC, yusufmsabeh commented on src/models/User.ts
> +      await user.$get("carts", {
Done✅

2023-07-23 06:59 UTC, mshareef-kiitos approved these changes

2023-07-23 07:02 UTC, merged